import Head from 'next/head'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import 'bootstrap-icons/font/bootstrap-icons.css';

import styles from '../styles/sass/Home.module.scss'
import Layout from '@/components/Layout'
import Table from '@/components/Table'

import Button from '@/components/Button';
import Form from '@/components/Form';
import useClients from '@/hooks/useClients';
import useLayout from '@/hooks/useLayout';


export default function Home() {

  const {
    mode,
    ToggleMode,
    client,
    clients,
    SelectedClient,
    DeletedClient,
    SaveClient,
    NewClient
  } = useClients()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          <Layout title="Simple Registration">
            <div className={styles['tool-bar']}>
              {/* <Button onClick={() => DataLoad()}>
                Data Load
              </Button> */}
              {
                mode ?
                  <Button onClick={() => NewClient()}>
                    New Client
                  </Button>
                  :
                  false
              }
            </div>
            {
              mode ?
                <Table
                  clients={clients}
                  selectClient={SelectedClient}
                  deletedClient={DeletedClient}></Table>
                :
                <Form
                  client={client}
                  cancel={() => ToggleMode()}
                  save={SaveClient} />
            }
          </Layout>
        </div>
      </main>
    </>
  )
}
